### ISSUE TITLE
First message on topic swallowed

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/rosduct#3]
Whether that is in rosduct itself of the topic_tools/relay node I don't know yet. This is a problem for actionlib topics.

Workaround for now:
Use axclient to trigger each remote action at least once from the server. And then cancel that goal. That ensures that it's all initialised correctly.

**Comment by marc-hanheide** [comment]
To clarify it's only the first ever sent message (when a topic is still untyped). After that, it works fine and completely reliable.

**Comment by marc-hanheide** [comment]
done some further investigation:

the problem cannot be reproduced with a simple rostopic echo/pub setup. There it works. This indicates that as long as both the rosbridge_server and rosduct are started *before* any publisher/subscriber connect, it works fine. The only problem appears to be when publishers and subscribers already exist and the rosduct tunnel is started later. This indicates we should first establish the communication infrastructure and the start the rest of the system.

**Comment by gpdas** [comment]
This is a not a bug (even without topic latching), but a configuration error in rasberry. The variable names were mentioned wrongly. It is not clear whether topic_tools was part of the problem. With the correct rosduct config, topic_tools is no longer required, and it is working without any problems (tested in simulation so far).

**Comment by marc-hanheide** [comment]
Good, so we close this
